- name: install security controls debian
  tags:
   - configuration
   - security
  apt: name={{ item }} state=present
  with_items:
   - chkrootkit
   - rkhunter
   - clamav
   - fail2ban
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" 
  

- name: install basic utilities debian
  tags:
   - configuration
  apt: name={{ item }} state=present
  with_items:
   - vim
   - screen
   - iotop
   - htop
   - ioping
   - ntp
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

