# This playbook install the apps required in a server

- name: install splunk binary
  tags:
   - install
  apt: deb=/tmp/splunk/{{splunk_binary}}

- name: copy user-seed.conf
  template: src=opt/splunk/etc/system/local/user-seed.conf dest=/opt/splunk/etc/system/local/user-seed.conf owner=splunk group=splunk mode=600 
  tags:
   - install

- name: copy deploymentclient.conf
  template: src=opt/splunk/etc/system/local/deploymentclient.conf dest=/opt/splunk/etc/system/local/deploymentclient.conf owner=splunk group=splunk mode=600 
  tags:
   - install

- name: accept license
  tags:
   - install
  shell: /opt/splunk/bin/splunk start --accept-license 

- name: enable init script
  tags:
   - install
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk