# This playbook install the apps required in a server

- name: install splunk binary
  tags:
   - install
  apt: deb=/tmp/splunk/{{splunk_binary}}

- name: copy user-seed.conf
  template: src=opt/splunk/etc/system/local/user-seed.conf dest=/opt/splunk/etc/system/local/user-seed.conf owner=splunk group=splunk mode=600 
  tags:
   - install

- name: copy deploymentclient.conf
  template: src=opt/splunk/etc/system/local/deploymentclient.conf dest=/opt/splunk/etc/system/local/deploymentclient.conf owner=splunk group=splunk mode=600 
  tags:
   - install

- name: copy web.conf
  template: src=opt/splunk/etc/system/local/web.conf dest=/opt/splunk/etc/system/local/web.conf owner=splunk group=splunk mode=600
  tags:
   - install

- name: copy server.conf
  template: src=opt/splunk/etc/system/local/server.conf dest=/opt/splunk/etc/system/local/server.conf owner=splunk group=splunk mode=600
  tags:
    - install

- name: copy splunk passwd file
  tags:
   - install
   - security
  copy: src=splunk_creds/passwd dest=/opt/splunk/etc owner=splunk group=splunk mode=700

- name: copy indexes.conf 
  tags:
   - install
  copy: src=opt/splunk/etc/system/local/indexes.conf dest=/opt/splunk/etc/system/local owner=splunk group=splunk mode=755

- name: copy inputs.conf 
  tags:
   - install
   - security
  copy: src=opt/splunk/etc/system/local/inputs.conf dest=/opt/splunk/etc/system/local owner=splunk group=splunk mode=755

- name: copy outputs.conf
  tags:
   - install
   - security
  copy: src=opt/splunk/etc/system/local/outputs.conf dest=/opt/splunk/etc/system/local owner=splunk group=splunk mode=755

- name: copy splunk sudoers
  template: src=etc/sudoers.d/splunk dest=/etc/sudoers.d/splunk owner=root group=root mode=440
  tags:
    - install

- name: accept license
  tags:
   - install
  shell: sudo -u splunk /opt/splunk/bin/splunk start --accept-license 

- name: enable init script
  tags:
   - install
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk