# This playbook install the apps required in a server

- name: install splunk binary
  tags:
   - install
  apt: deb=/tmp/splunk/{{splunk_binary}} 

- name: accept license
  tags:
   - install
  shell: /opt/splunk/bin/splunk start --accept-license 

- name: enable init script
  tags:
   - install
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk

- name: configure phone home
  tags:
   - install
  shell: /opt/splunk/bin/splunk set deploy-poll {{deploy_server}}