---
# This playbook sets up basic splunk security 
- name: copy splunk passwd file
  tags:
   - install
   - security
  copy: src=splunk_creds/passwd dest=/opt/splunk/etc owner=splunk group=splunk mode=700
