---
# The main playbook to deploy your entire splunk infrastructure from hosts file

- name: apply common configuration to all nodes
  hosts: common
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - common
