---
# This playbook deploys all sub playbooks

- name: apply common configuration to all nodes
  hosts: splunk-prod-search-head
  become: yes
  become_user: root
  become_method: sudo
  vars:
    # splunk binary to install
    splunk_binary: 'splunk-6.2.0-237341-Linux-x86_64.tgz'

  roles:
    - common
    - search_head


