---
# This playbook deploys all sub playbooks

- name: apply common configuration to all nodes
  hosts: splunk-prod-forwarders
  vars:
    - splunk_binary: 'splunkforwarder-7.2.3-06d57c595b80-linux-2.6-amd64.deb'
  become: yes
  become_user: root
  become_method: sudo
  vars:
    # splunk universal forwarder binary to install
    splunk_uf_binary: 'splunkforwarder-6.2.0-237341-Linux-x86_64.tgz'

  roles:
    - common
    - universal_forwarder


